# Generated by Django 5.1.1 on 2024-10-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
