# Generated by Django 5.1.1 on 2024-10-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_pedido_endereco_remove_pedido_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_intent',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
